# Generated by Django 4.0.1 on 2023-03-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_alter_articles_writer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='contnt',
            field=models.TextField(default=None),
        ),
    ]
