# Generated by Django 4.0.1 on 2023-03-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_articles_contnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllPosts',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='img',
            new_name='writer_img',
        ),
        migrations.AddField(
            model_name='articles',
            name='visual',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='News'),
        ),
    ]
